### PR TITLE
Added wider unix color compatibility with VT100 16-bit colors

### PR DESCRIPTION
**Pull request by Spartan322**
Changed grid of people from vector simulating a grid to a more grid like object 
Adjusted .gitignore to disregard compiled file changes
Adjusted the CMakeLists.txt thread reference to correspond to Threads::Threads
Added Default value to TextColour enum (also saving the first default attribute scheme on windows)

### CODE REVIEW

**Comment by Hopson97** [comment]
I like your changes, they will increase readability :) (as well as work on Unix for the colours which is always nice)

One thing I am confused about is line 210 on World.cpp, you call "Grid::init" but I see no "init" function in the Grid class when looking at the changed files. Was this accidentally removed?

Thanks for the interest in my project though :)

**Comment by Spartan322** [comment]
The init is in reference to the Person object contained within the grid.

**Comment by Hopson97** [comment]
Oh right! I feel silly now.

Looks good to pull!

**Comment by Hopson97** [comment]
I mean merge. 

Thanks!

**Pull request merged**
